name = "LastfmHugoDemo"
license = "MIT"
licenselink = "https://github.com/alrayyes/lastfm-hugo-demo-theme/blob/master/LICENSE.md"
description = "Theme that demonstrates Hugo & Last.fm api working together"
homepage = "https://github.com/alrayyes/lastfm-hugo-demo-theme"
tags = ["lastfm", "demo", "last.fm"]
features = ["lastfm", "last.fm"]
min_version = 0.15

[author]
  name = "Ryan Kes"
  homepage = "https://ryankes.eu"
